linters:
  enable: 
    - lll
    - wsl
    - gochecknoglobals
    - revive
    - gocritic
    - errname
    - godot
linters-settings:
  lll:
    line-length: 80  # Set your preferred line length limit for comments
