name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  prep:
    runs-on: ubuntu-latest

    outputs:
      client: ${{ steps.filter.outputs.client }}
      java_server: ${{ steps.filter.outputs.java_server }}

    steps:
      - name: Filter Directory
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            client:
              - 'client/**'
            java_server:
              - 'java_server/**'

      - name: Debug Output
        run: echo ${{ toJson(steps.filter.outputs.changes) }}

  build-client:
    needs: prep

    runs-on: ubuntu-latest

    if: ${{ needs.prep.outputs.client == 'true' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Dependencies
        run: flutter pub get
        working-directory: client

      - name: Tests
        run: flutter test
        working-directory: client
