name: Build

on:
  pull_request:
    branches: [main]

jobs:
  prep:
    runs-on: ubuntu-latest

    outputs:
      client: ${{ steps.filter.outputs.client }}
      server: ${{ steps.filter.outputs.server }}

    steps:
      - name: Filter Directory
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            client: ['client/**']
            server: ['server/**']

  build-client:
    needs: prep

    if: ${{ needs.prep.outputs.client == 'true' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Dependencies
        run: flutter pub get
        working-directory: client

      - name: Tests
        run: flutter test
        working-directory: client

  build-server:
    needs: prep

    if: ${{ needs.prep.outputs.server == 'true' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build
        run: ./gradlew build
        working-directory: server
