name: Build

on:
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Build
        run: go build -v ./...
        working-directory: server/cmd

      - name: Test
        run: go test -v ./...
        working-directory: server/cmd
